server:
  port: 8082
# 微服务的application.yml
shopease:
  redis:
    host: 10.20.140.36
    port: 6379
    password: redis123456
    database: 0
    pool:
      max-active: 16
      max-idle: 8
      min-idle: 4
      max-wait: 2000
