server:
  port: 8082
# 微服务的application.yml
shopease:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    pool:
      max-active: 16
      max-idle: 8
      min-idle: 4
      max-wait: 2000
